export const MAIL_QUEUE = 'MAIL_QUEUE';
export const REGISTRATION_CONFIRM = 'REGISTRATION_CONFIRM';
export const REGISTRATION_CONFIRMED = 'REGISTRATION_CONFIRMED';
export const INVITE_USER = 'INVITE_USER';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
